Set target dir, copy file url, more file info, other changes
DirectoryLister/DirectoryLister pull request #541
Opened 2021-01-10 22:35 UTC by olfek

Dumping this here, it is late right now, I will edit this description tomorrow.

2021-01-11 04:32 UTC, PHLAK requested changes
Please break these changes up into individual pull requests (one PR per feature).

2021-01-11 08:03 UTC, olfek commented
Hello, I only have one squashed commit, to create multiple PRs I will need to break it down into smaller commits first.

I'm concerned that doing this may break things and it's worth noting that the current state of the code has been throughly tested manually.

I will update the description of the PR this evening so you have a better idea of the work that has been done.

Thank you for your prompt response 🙂

2021-01-11 20:56 UTC, olfek commented
@PHLAK I have added a description :slightly_smiling_face:

2021-01-12 02:45 UTC, PHLAK commented
First, thank you for the PR.  I appreciate the time and effort that goes into every PR. Unfortunately, I will not be accepting this combined pull request. If you wish to separate this into separate PRs I will review them individually. I will, however give my initial thoughts about each feature without digging in too deep.

### 1. Ability to set target directory (home/root/base path)

I'd love to find a way to do this but would need to review the individual PR for this feature before making any decisions.

### 2. More file info in the file info popup

What additional info?

### 3. Configurable hashing algorithms.

This isn't something I wish to change at this time.

### 4. The page title no longer contains •.

>  in the case of an empty SITE_TITLE, their is no trailing symbol

While I agree it would be nice to hide the bullet if `SITE_TITLE` is empty the bullet is used as a separator between the path and site title when present and I don't want to remove it from the code.

### 5. Ability to copy the URL of a file.

Would need to review the individual PR for this feature before making any decisions.

2021-01-12 02:45 UTC, closed without merging

2021-01-12 08:22 UTC, olfek commented
Hello, why has this been closed? @PHLAK

2021-01-12 10:18 UTC, olfek commented on app/src/Controllers/FileInfoController.php
> +                    ['size' => Utils::sizeForHumans($file)] +
@PHLAK Regarding feature number 2
> What additional info?

This additional info

2021-01-12 10:19 UTC, olfek commented
@PHLAK Why do you not wish to have feature number 3?

2021-01-12 10:23 UTC, olfek commented
@PHLAK Regarding feature number 4
> While I agree it would be nice to hide the bullet if SITE_TITLE is empty the bullet is used as a separator between the path and site title when present and I don't want to remove it from the code.

Now that the bullet has been removed, users can add their own symbol into `SITE_TITLE` if they want to have a separator, this information can be added to the upgrade notes.

2021-01-12 10:26 UTC, olfek commented on app/config/app.php
> +    'site_title' => DI\env('SITE_TITLE', '• Directory Lister'),
The bullet has been moved here, so out of the box installations will still have a separator @PHLAK

2021-01-12 10:45 UTC, olfek commented
@PHLAK Also, FYI, when developing, and targeting an external directory, you want to set `FILE_URL_PREFIX` to a `localhost` address with a port different from the one the app is running on, then, start another server at that port for the sole purpose of serving files.

2021-01-12 10:51 UTC, olfek commented
@PHLAK I'd greatly appreciate if you could re-open this PR as I have spent over a week working on it 🙂

2021-01-12 15:24 UTC, PHLAK commented
@olfek I appreciate the time and effort that went into this and would like to work on getting some of this code merged into Directory Lister.

However, as I stated before I will not be accepting this combined PR. If you would separate this into individual PRs (one per feature) I can review and discuss them individually.

2021-01-12 15:36 UTC, olfek commented
> Hello, I only have one squashed commit, to create multiple PRs I will need to break it down into smaller commits first.
> 
> **I'm concerned that doing this may break things and it's worth noting that the current state of the code has been thoroughly tested manually.**
> 
> I will update the description of the PR this evening so you have a better idea of the work that has been done.
> 
> Thank you for your prompt response 🙂

@PHLAK See my earlier comment about this above, and besides, I don't want to spend anymore time on this as I have other things to do, all of the features I have offered to you in this PR _should_ be accepted in my opinion, they are all great improvements.

If you spend some time looking at the code, you will begin to feel more comfortable with the changes I have made 🙂

2021-01-12 15:43 UTC, PHLAK commented
I have looked at the code and wish to discuss some changes. However, I will not be doing that unless this PR is broken into individual PRs per feature. I will not ask again.

2021-01-12 15:48 UTC, olfek commented
@PHLAK Why can't you just review everything in this PR?

2021-01-12 15:50 UTC, olfek commented
@PHLAK You trying to make me do extra "red tape" work, don't be selective about the features and just review everything please 🙂

2021-01-12 16:00 UTC, olfek commented
Lets start to discuss the actual code @PHLAK 🙂 I look forward to seeing your comments on the code

2021-01-13 16:55 UTC, olfek commented
Hello? @PHLAK

2021-01-13 16:56 UTC, olfek commented
I really don't want to have to maintain a fork of this @PHLAK

2021-01-13 17:48 UTC, PHLAK commented
@olfek I have stated multiple times that I will review each feature individually once broken into separate PRs. This requirement is clearly defined in our [contributing guidelines](https://github.com/DirectoryLister/DirectoryLister/blob/master/.github/CONTRIBUTING.md) and I will not be making an exception in this case. Please stop spamming.